---
title: "House Prices"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\*\*\* REVISION NOTE: Check to see if necessary packages are installed.
If not, install them \*\*\*

```{r include=FALSE}
# lists all packages needed in this notebook
packages_list = list( 'tidyverse', 'corrplot', 'caTools', 'car',
                     'glmnet','caret','kknn','rpart','rpart.plot','randomForest',"pROC")
# checks to see if package is installed.  If not, installs and loads it 'knitr',
for (i in packages_list) {
  if (!require(i, character.only=TRUE)) install.packages(i, character.only=TRUE); library(i, character.only=TRUE)
}

# removes the assignment of i and packages_list
rm(i, packages_list)
```

## Overview

I have to set up the R package stuff but i'm just shit at it without hte template aren't i
what next?

## Preparing the Data

### Reading data

```{r read_data, message=FALSE}
# Set color codes
gtblue = rgb(0, 48, 87, maxColorValue = 255)
techgold = rgb(179, 163, 105, maxColorValue = 255)
buzzgold = rgb(234, 170, 0, maxColorValue = 255)
bobbyjones = rgb(55, 113, 23, maxColorValue = 255)

# Read the data using read_csv
htrain <- read.csv("train.csv",header=TRUE)
htest <- read.csv("test.csv",header=TRUE)
attach(htrain)
```

### General Data Prep
```{r}
# Remove Id column, it is not necessary
htrain = htrain[-1]
```

### Correlation among the numeric variables

```{r correlation}
# Select numerical variables
h.num <- na.omit(h.num[ , which(sapply(h.num, is.numeric))])
# Create correlation matrix
corr <- cor(h.num)
# Create correlation plot
col <- colorRampPalette(c(buzzgold,"white", gtblue))(10)
par(mfrow=c(1,1))
corrplot(corr, method = "number", type = "upper", tl.col="black", col = col)
```
### Categorical Variables

```{r data_prep}
# Convert categorical variables to factors
numnames <- colnames(h.num)
htrain <- htrain %>% mutate_at(vars(-c(numnames)), as.factor)
```


```{r}

```

